server:
  port: 8084

spring:
  application:
    name: logistics-warehouse
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_warehouse?characterEncoding=utf-8&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: "031500"
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.130:8848 # 注册地址
  redis:
    host: 192.168.195.130
    port: 6379
    database: 0
    timeout: 5000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_