server:
  port: 8081

spring:
  application:
    name: logistics-admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.130
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_admin?characterEncoding=utf-8&useSSL=false
    username: root
    password: "031500"
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.195.130
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_  # 设置表前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl