server:
  port: 8085

spring:
  application:
    name: logistics-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.130
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics_admin?characterEncoding=utf-8&useSSL=false
    username: root
    password: "031500"
  servlet:
    multipart:
      max-file-size: 100MB  # 设置文件所能经过的最大数量
      max-request-size: 100MB  # 设置请求所能经过的最大请求量
  redis:
    host: 192.168.195.130
    port: 6379
    database: 0
    timeout: 5000ms

# 七牛云密钥
qiniu:
  accessKey: xxx
  accessSecretKey: xxx
# 容联云密钥
cloopen:
  serverIp: app.cloopen.com
  serverPort: 8883
  appId: xxx  # 管理控制台中的 appId
  accountSId: xxx # 开发者id
  accountToken: xxx # 开发者密钥